### ISSUE TITLE
undefined method `before_action' for UsersController(Table doesn't exist):Class

### ISSUE THREAD

**Issue by mrsdo** [Marti-Dolce-Flatiron-School-Projects/P3-Use-Case-Model-Relationship-Building#19]
Need to include an if no records then conditional for models.  Currently, rails generates this error if no records found.

1 2 3 4 5 6 | class UsersController < ActiveRecord::Base   before_action :set_user, only: %i[ show edit update destroy ]    # GET /users or /users.json   def index     @users = User.all
-- | --

Application Trace | Framework Trace | Full Trace
app/controllers/users_controller.rb:2:in `<class:UsersController>'
app/controllers/users_controller.rb:1:in `<top (required)>'

**Comment by mrsdo** [comment]
I initially thought this was related to no data.  After seeding the users table, I'm still getting the error undefined method [`before_action'](https://stackoverflow.com/questions/46292192/undefined-method-skip-before-action-when-skipping-authentication-in-devise).
